# --- Change what appears in the banner --- #
title: My Language Learning Website
description: This is the tag-line of my website.

# --- Change language of site --- #
lang: en

# --- List of links in the navigation bar --- #
# --- Change only the black entry if you change the name of your .md files!! --- #
github:
  page1: index.html
  page2: page2.html
  page3: page3.html
  page4: page4.html
  page5: page5.html
