title: My Language Learning Website
description: This is the tag-line of my website.
lang: en
google_analytics:
#theme: jekyll-theme-cayman
github:
  page1: index.html
  page2: page2.html
  page3: page3.html
  page4: page4.html
  page5: page5.html
  
